HelloQQPortal/Controllers/adminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Net;
using System.IO;
using HelloQQPortal.Database;
using HelloQQPortal.Manager;
using HelloQQPortal.Models;
using System.Web.Configuration;
using System.Collections.Specialized;
using System.Globalization;
using System.Web.Routing;

namespace HelloQQPortal.Controllers
{
    public class adminController : Controller
    {
        private MemberManager memberMgr;
        private ImageManager imageMgr;
        private ProductManager productManager;
        private ProductFaqManager productFaqManager;
        private ProductManualManager productManualMgr;
        private UIManager uiManager;

        private NameValueCollection webConfig = WebConfigurationManager.AppSettings;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            uiManager = new UIManager();
            uiManager.ValidatePermission(this.ToString());
        }

        // GET: Admin
        public ActionResult Index()
        {
            ViewBag.Message = "Administrator.";
            ViewBag.Message = "Your application description page.";
            return View();
        }

        public ActionResult MemberList()
        {
            memberMgr = new MemberManager();
            return View(memberMgr.GetMemberList());
        }

        // GET: Admin
        public ActionResult MemberDetail(int? id)
        {
            MemberInfo memberInfo = new MemberInfo();
            hqq_member member;
            memberMgr = new MemberManager();
            productManager = new ProductManager();

            memberInfo.MemberDetail = new hqq_member();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            member = memberMgr.GetMemberById(id.Value);


            if (member == null)
            {
                return HttpNotFound();
            }

            memberInfo.MemberDetail = member;
            if (member.hqq_member_product.Count > 0)
            {
                memberInfo.MemberProduct = member.hqq_member_product.ToList();
            }
            memberInfo.ProductList = productManager.GetProductList();

            return View(memberInfo);
        }

        [HttpPost]
        public ActionResult UpdateMemberDetail(MemberInfo memberInfo, string command)
        {
            string rtnURL = "/admin/member";
            memberMgr = new MemberManager();

            try
            {
                if (command.Equals("updateMemberProduct"))
                {
                    if (memberInfo.SelectedProductId > 0)
                    {
                        hqq_member_product mpInfo = new hqq_member_product();

                        mpInfo.member_id = memberInfo.MemberDetail.id;
                        mpInfo.product_id = memberInfo.SelectedProductId;
                        mpInfo.purchase_date = DateTime.ParseExact(memberInfo.PurchasedOn, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                        mpInfo.garantee_expired = mpInfo
                            .purchase_date.AddMonths(
                            int.Parse(webConfig["product.garantee"]));

                        memberMgr.UpdateMemberProduct(mpInfo);

                        //memberProductInfo.garantee_expired = 
                        //memberInfo.PurchasedOn
                        //memberProductInfo.purchase_date =                       
                    }
                }
                else if (command.Contains("cancel-purchase"))
                {
                    string selectedId = command.Split('.')[1];
                    memberMgr.DeleteMemberProduct(int.Parse(selectedId));
                }
                else
                {
                    memberMgr.UpdateMember(memberInfo.MemberDetail);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

            if (memberInfo.MemberDetail.id > 0)
            {
                rtnURL = rtnURL + "/" + memberInfo.MemberDetail.id;
            }

            return Redirect(rtnURL);

        }

        [HttpPost]
        public ActionResult UpdateMemberProduct(MemberInfo memberInfo)
        {
            string rtnURL = "/admin/member";
            hqq_member_product mpInfo;
            memberMgr = new MemberManager();

            try
            {
                mpInfo = memberInfo.MemberProduct.FirstOrDefault();
                if (mpInfo != null)
                {
                    mpInfo.member_id = memberInfo.MemberDetail.id;
                    mpInfo.purchase_date = DateTime.ParseExact(memberInfo.PurchasedOn, "dd/MM/yyyy", CultureInfo.InvariantCulture);
                    mpInfo.garantee_expired = mpInfo
                        .purchase_date.AddMonths(
                        int.Parse(webConfig["product.garantee"]));

                    memberMgr.UpdateMemberProduct(mpInfo);

                    //memberProductInfo.garantee_expired = 
                    //memberInfo.PurchasedOn
                    //memberProductInfo.purchase_date = 
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }

            if (memberInfo.MemberDetail.id > 0)
            {
                rtnURL = rtnURL + "/" + memberInfo.MemberDetail.id;
            }

            return Redirect(rtnURL);
        }

        // GET: Admin
        public ActionResult ProductList()
        {
            productManager = new ProductManager();
            List<hqq_product> lstProductInfo = productManager.GetProductList();
            return View(lstProductInfo);
        }

        // GET: Admin
        public ActionResult ProductDetail(int? id)
        {
            productManager = new ProductManager();

            ProductInfo productInfo = new ProductInfo();

            if (id.HasValue && id.Value > 0)
            {
                productInfo.ProductDetail = productManager.GetProductById(id.Value);
                if (productInfo.ProductDetail.hqq_product_images.Count() > 0)
                {

                    productInfo.ProductImage = productInfo.ProductDetail.hqq_product_images.FirstOrDefault();
                    FileInfo fileInfo = new FileInfo(productInfo.ProductImage.url);
                    productInfo.ProductImageThumbURL = string.Format("{0}/thmb-{1}",
                        productInfo.ProductImage.url.Substring(0, productInfo.ProductImage.url.LastIndexOf("/"))
                        , fileInfo.Name, fileInfo.Extension);
                }
            }
            else
            {
                productInfo.ProductDetail = new hqq_product();
            }

            return View(productInfo);
        }

        [HttpPost]
        public ActionResult UpdateProductDetail(ProductInfo productInfo)
        {
            productManager = new ProductManager();

            hqq_product productDetail = productInfo.ProductDetail;
            string rtnURL = "/admin/product";

            try
            {
                if (productDetail.id == 0)
                {
                    productDetail.created_on = DateTime.Now;
                    productDetail.created_by = 1;
                    productDetail = productManager.UpdateProductDetail(productDetail);

                }
                else
                {
                    productDetail.modified_on = DateTime.Now;
                    productDetail.modified_by = 1;
                    productDetail = productManager.UpdateProductDetail(productDetail);

                }

                if (productInfo.ImageUpload != null && productDetail.id > 0)
                {
                    productManager.AddProductImage(
                        productInfo.ProductDetail,
                        productInfo.ImageUpload);

                }
            }
            catch (Exception)
            {
                return View(productInfo);
            }

            if (productInfo.ProductDetail.id > 0)
            {
                rtnURL = rtnURL + "/" + productInfo.ProductDetail.id;
            }

            return Redirect(rtnURL);
        }

        public ActionResult ProductManualList()
        {
            this.productManualMgr = new ProductManualManager();

            List<hqq_product_manual> lstProductManual = productManualMgr.GetProductManualList();
            return View(lstProductManual);
        }

        // GET: Admin
        public ActionResult ProductManualDetail(int? id)
        {
            productManualMgr = new ProductManualManager();
            productManager = new ProductManager();

            ProductManualInfo productManualInfo = new ProductManualInfo();
            productManualInfo.ProductManual = new hqq_product_manual();
            productManualInfo.ProductList = productManager.GetProductList();

            if (id.HasValue)
            {
                productManualInfo.ProductManual = productManualMgr.GetProductManualById(id.Value);
                productManualInfo.ProductManualContent = productManualInfo.ProductManual.content;
                productManualInfo.SelectedProductId = productManualInfo.ProductManual.product_id;
                productManualInfo.ProductManualImage = productManualMgr.GetManualImagesList(id.Value);
            }
            return View(productManualInfo);
        }


        [HttpPost]
        // GET: Admin
        public ActionResult UpdateProductManualDetail(ProductManualInfo productManualInfo)
        {
            this.productManualMgr = new ProductManualManager();

            hqq_product_manual productManual = new hqq_product_manual();

            string rtnURL = "/admin/product-manual";
            string strProductImg = "";

            if (productManualInfo.ProductManual.id > 0)
            {

HelloQQPortal/Controllers/productController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using HelloQQPortal.Database;
using HelloQQPortal.Manager;
using HelloQQPortal.Models;


namespace HelloQQPortal.Controllers
{
    public class productController : Controller
    {
        private UIManager uiManager;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            uiManager = new UIManager();
            uiManager.ValidatePermission(this.ToString());
        }

        // GET: Product
        public ActionResult Index()
        {
            hqq_member memeberInfo;
            List<MemberProductInfo> lstMemberPrdInfo = new List<MemberProductInfo>();
            MemberProductInfo memberPrdInfo = new MemberProductInfo();

            if (Session["memberInfo"] != null)
            {
                memeberInfo = (hqq_member)Session["memberInfo"];

                List<hqq_product> lstHqqProductInfo = new List<hqq_product>();
                List<int> lstSelectItem = new List<int>();

                ProductManager productMgr = new ProductManager();
                ProductManualManager productManualMgr = new ProductManualManager();

                List<hqq_member_product> lstMemberProduct = productMgr.GetMemberProduct(memeberInfo.id);
                if (lstMemberProduct.Count > 0)
                {
                    lstSelectItem = lstMemberProduct.Select(item => item.product_id).ToList();
                    lstSelectItem = productManualMgr.CheckAvailableManual(lstSelectItem);

                    foreach (var item in lstMemberProduct)
                    {                        
                        memberPrdInfo = new MemberProductInfo();
                        memberPrdInfo.ProductId = item.product_id;
                        memberPrdInfo.ProductName = item.hqq_product.name;
                        memberPrdInfo.ProductDesc = item.hqq_product.description;

                        memberPrdInfo.PurchaseDate = item.purchase_date;
                        memberPrdInfo.GuaranteeExpire = item.garantee_expired;

                        memberPrdInfo.ProductImagesId = item.hqq_product.hqq_product_images.Select(selecteItem => selecteItem.id).ToList();
                        memberPrdInfo.HaveManual = lstSelectItem.Contains(item.product_id);

                        lstMemberPrdInfo.Add(memberPrdInfo);
                    }
                }
               
            }        

            return View(lstMemberPrdInfo);
        }

        public ActionResult View(int id)
        {
            return View();
        }

        public ActionResult Manual(int? id)
        {
            ManualFaqInfo manualFaqInfo = new ManualFaqInfo();

            //if(Session["memberInfo"] == null)
            //{
            //    Response.Redirect("/home/login");
            //}

            // Check Session Info
            // Check Product Id  with product member info

            if (id.HasValue)
            {
                ProductManualManager productManualMgr = new ProductManualManager();
                ProductFaqManager productFaqMgr = new ProductFaqManager();

                manualFaqInfo.ManualInfo = productManualMgr.GetProductManualByProductId(id.Value);
                manualFaqInfo.FaqInfoList = productFaqMgr.GetFaqByProductId(id.Value);

                if (manualFaqInfo.ManualInfo.id > 0)
                {
                    ViewBag.Message = manualFaqInfo.ManualInfo.subject;
                }
            }
            else
            {
                Response.Redirect("/home");
            }

            return View(manualFaqInfo);
        }

        public ActionResult FAQ()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    }
}

HelloQQPortal/Views/admin/faqList.cshtml
@model IEnumerable<HelloQQPortal.Database.hqq_product>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>การจัดการคู่มือ</h2>

<p>
    <i class="fas fa-camera-retro fa-2x"></i>
    @*@Html.ActionLink("Create New", "productDetail","admin")*@
    <a href="/admin/productManualDetail">สร้างคู่มือสินค้า</a>
</p>

<table class="admin table">
    <tr>
        <th>
            ไอดี
        </th>
        <th>
            สินค้า
        </th>
        <th>
            สร้างเมื่อ
        </th>
        <th>
            แก้ไขเมื่อ
        </th>
        <th>
            สถานะ
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.subject)
                </td>

                <td>
                    @item.created_on.ToString("dd MMM yyyy")
                </td>
                <td>
                    @if (item.modified_on.HasValue)
                    {
                        @item.modified_on.Value.ToString("dd MMM yyyy");
                    }
                </td>
                <td>
                    @((item.status == 1) ? "ใช้งาน" : "ปิดการใช้งาน")

                </td>
                <td>
                    <a href="/admin/product-manual/@item.id">แก้ไข</a>
                    @*@Html.ActionLink("Edit", "userdetail", new { id = item.id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })*@
                </td>
            </tr>
        }
    }

</table>

HelloQQPortal/Views/admin/manualList.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

HelloQQPortal/Views/admin/memberDetail.cshtml
@model HelloQQPortal.Models.MemberInfo

@{
    ViewBag.Title = "การจัดการผู้ใช้งาน";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>แก้ไขผู้ใช้งาน</h2>

<div style="padding-left:40px;">
    @using (Html.BeginForm("UpdateMemberDetail", "admin", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal admin">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.MemberDetail.id)

            <div class="form-group row">
                @Html.Label("recordId", "หมายเลขเร็คคอร์ท", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    @Html.LabelForModel(Model.MemberDetail.facebook_name, htmlAttributes: new { @class = "form-label" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("facebookId", "หมายเลข Facebook", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.LabelForModel(Model.MemberDetail.facebook_id, htmlAttributes: new { @class = "form-label" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("facebookName", "ชื่อใน Facebook", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.LabelForModel(Model.MemberDetail.facebook_name, htmlAttributes: new { @class = "form-label" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("memberName", "ชื่อสมาชิก", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MemberDetail.fullname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MemberDetail.fullname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("address", "ที่อยู่ในการจัดส่งสินค้า", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.MemberDetail.address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MemberDetail.address, "", new { @class = "text-danger" })

                </div>
            </div>

            <div class="form-group row">
                @Html.Label("createdOn", "สมัครเมื่อ", htmlAttributes: new { @class = "col-sm-2 col-form-label" })

                <div class="col-md-10">
                    <label class="form-label">@Model.MemberDetail.created_on.ToString("dd MMM yyyy HH:mm:ss") </label>
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("modifiedOn", "อัพเดทล่าสุด", htmlAttributes: new { @class = "col-sm-2 col-form-label" })

                <div class="col-md-10">
                    <label class="form-label"> @(Model.MemberDetail.modified_on.HasValue ? Model.MemberDetail.modified_on.Value.ToString("dd MMM yyyy HH:mm:ss") : "") </label>
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("modifiedOn", "สินค้าผู้ใช้งาน", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    <div class="form-row align-items-center">
                        <div class="form-row align-items-center">
                            <div class="col-sm-5 my-1">
                                @Html.DropDownListFor(model => model.SelectedProductId,
                                     new SelectList(Model.ProductList,
                                     "id", "name",
                                     Model.SelectedProductId),
                                     new { @class = "custom-select", id = "ddlProduct" })
                            </div>
                            <div class="col-sm-4 my-1">
                                <label class="sr-only" for="inlineFormInputGroupUsername">Username</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text"></div>
                                    </div>
                                    @Html.EditorFor(model => model.PurchasedOn,
                                        new
                                        {
                                            htmlAttributes = new
                                            {
                                                @Value = Model.MemberDetail.created_on.ToString("dd/MM/yyyy"),
                                                @class = "form-control",
                                                id = "txtPurchaseDate"
                                            }
                                        })
                                </div>
                            </div>

                            <div class="col-auto my-1">
                                <button type="submit" name="Command" value="updateMemberProduct" class="btn btn-primary btn-md active">เพิ่มสินค้า</button>
                            </div>
                        </div>
                    </div>
                    <table class="table table-sm" style="margin-top:5px;">
                        <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">สินค้า</th>
                                <th scope="col">วันที่ซื้อ</th>
                                <th scope="col">วันที่หมดประกัน</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                              @if (Model.MemberProduct != null)
                            {
                                foreach (var item in Model.MemberProduct)
                                {
                            <tr>
                                <th scope="row"> @Html.DisplayFor(modelItem => item.id)</th>
                                <td>@Html.DisplayFor(modelItem => item.hqq_product.name)</td>
                                <td>@item.purchase_date.ToString("dd MMM yyyy")</td>
                                <td>@(item.garantee_expired.HasValue ? item.garantee_expired.Value.ToString("dd MMM yyyy") : "-")</td>
                                <td><button type="submit" name="Command" value="cancel-purchase.@item.id" class="btn btn-outline-danger btn-sm">ยกเลิกการสั่งซื้อ</button></td>

                            </tr>
                             }
                            }
                        </tbody>
                    </table>
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("role", "ระดับผู้ใช้งาน", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10" style="padding-top:6px;">
                    @*@Html.EditorFor(model => model.MemberDetail.status, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MemberDetail.status, "", new { @class = "text-danger" })*@

                    @Html.DropDownListFor(model => model.MemberDetail.role, new List<SelectListItem>
                                    {
                                        new SelectListItem{ Text="ผู้ดูแล", Value = "99" },
                                        new SelectListItem{ Text="สมาชิก", Value = "1" }
                                    },
                               htmlAttributes: new { @class = "custom-select" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("status", "สถานะผู้ใช้", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10" style="padding-top:6px;">
                    @*@Html.EditorFor(model => model.MemberDetail.status, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MemberDetail.status, "", new { @class = "text-danger" })*@

                    @Html.DropDownListFor(model => model.MemberDetail.status, new List<SelectListItem>
                                    {
                                        new SelectListItem{ Text="ใช้งาน", Value = "1" },
                                        new SelectListItem{ Text="ระงับการใช้งาน", Value = "0" }
                                    },
                               htmlAttributes: new { @class = "custom-select" })
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    &nbsp;
                </div>
                <div class="col-md-10">
                    <input type="submit" value="บันทึก" class="btn btn-primary btn-md active" />
                    <a href="/admin/member" class="btn btn-primary btn-md active">กลับหน้าหลัก</a>
                    @*@Html.ActionLink("กลับหน้าหลัก", "userList", "admin", new { @class = "btn btn-primary btn-md active", @role = "button" })*@
                </div>
            </div>

        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}
<script>
    $(function () {
        $('#txtPurchaseDate').datepicker({ dateFormat: 'dd/mm/yy' });
    });
</script>

HelloQQPortal/Views/admin/productDetail.cshtml
@*@model HelloQQPortal.Database.hqq_product*@
@model HelloQQPortal.Models.ProductInfo

@{
    ViewBag.Title = "การจัดการสินค้า";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>การจัดการสินค้า</h2>

<div style="padding-left:40px;">
    @using (Html.BeginForm("UpdateProductDetail", "admin", FormMethod.Post, new { id = "frmInput", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal admin">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @if (Model.ProductDetail.id > 0)
            {
                @Html.HiddenFor(model => model.ProductDetail.id)
                @Html.HiddenFor(model => model.ProductDetail.created_by)

                <div class="form-group row">
                    @Html.Label("recordId", "ไอดี", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-10">
                        @Html.LabelForModel(Model.ProductDetail.id.ToString(), htmlAttributes: new { @class = "form-label" })
                    </div>
                </div>
            }
            <div class="form-group row">
                @Html.Label("productName", "ชื่อสินค้า", htmlAttributes: new { @class = "col-sm-2 col-form-label", id = "txtProductName" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ProductDetail.name, new { htmlAttributes = new { @class = "form-control", required = "required", oninvalid = "this.setCustomValidity('โปรดกรอกชื่อสินค้า')" } })
                    @Html.ValidationMessageFor(model => model.ProductDetail.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("productDescription", "รายละเอียดสินค้า", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.ProductDetail.description, new { htmlAttributes = new { @class = "form-control", id = "txtProductDesc", required = "required", oninvalid = "this.setCustomValidity('โปรดกรอกรายละเอียดสินค้า')" } })
                    @Html.ValidationMessageFor(model => model.ProductDetail.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                @Html.Label("productDescription", "รูปภาพสินค้า", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10">
                    @if (!string.IsNullOrEmpty(Model.ProductImageThumbURL))
                    {
                        <image src="@Url.Content(Model.ProductImageThumbURL)" style="width:100px;"></image>
                    }
                    @*<img src="@Url.Content("~/content/images/000001/sq-Xventure2-001.png")" style="width:100px;"/>*@
                    @*<label class="custom-file">
                            @Html.TextBoxFor(m => m.ImageUpload, new { type = "file", @class = "custom-file-input" })
                            <span class="custom-file-control"></span>
                        </label>*@
                    <br />
                    <div class="custom-file">
                        @Html.TextBoxFor(m => m.ImageUpload, new { type = "file", @class = "custom-file-input" })
                        <label class="custom-file-label" for="customFile">Choose file</label>
                    </div>
                </div>
            </div>

            @if (Model.ProductDetail.id > 0)
            {
                <div class="form-group row">
                    @Html.Label("createdOn", "ลงเมื่อ", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                    <div class="col-md-10">
                        <label class="form-label">@Model.ProductDetail.created_on.ToString("dd MMM yyyy HH:mm:ss") </label>
                    </div>
                </div>

                <div class="form-group row">
                    @Html.Label("modifiedOn", "อัพเดทล่าสุด", htmlAttributes: new { @class = "col-sm-2 col-form-label" })

                    <div class="col-md-10">
                        <label class="form-label">
                            @(Model.ProductDetail.modified_on.HasValue
                                                                    ? Model.ProductDetail.modified_on.Value.ToString("dd MMM yyyy HH:mm:ss") : "")
                        </label>
                    </div>
                </div>
            }


            <div class="form-group row">
                @Html.Label("status", "สถานะผู้ใช้", htmlAttributes: new { @class = "col-sm-2 col-form-label" })
                <div class="col-md-10" style="padding-top:6px;">
                    @Html.DropDownListFor(model => model.ProductDetail.status, new List<SelectListItem>
                                                                    {
                                                                        new SelectListItem{ Text="ใช้งาน", Value = "1" },
                                                                        new SelectListItem{ Text="ไม่ใช้งาน", Value = "0" }
                                                                    },
                                                          htmlAttributes: new { @class = "custom-select" });
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    &nbsp;
                </div>
                <div class="col-md-10">
                    <input type="submit" value="บันทึก" class="btn btn-primary btn-md active" />
                    @*<input type="button" value="กลับหน้าหลัก" class="btn btn-default" />*@
                    @*@Html.ActionLink("กลับหน้าหลัก", "product", "admin", new { @class = "btn btn-primary btn-md active", @role = "button" })*@
                    <a href="/admin/product" role="button" class="btn btn-primary btn-md active">กลับหน้าหลัก</a>
                </div>
            </div>
        </div>
    }
</div>